# netlify.toml

[build]
  command = "npm run build && (cd client && npm install && npm run build)"
  publish = "server/dist"  # Adjust the publish directory based on your setup

# Add other configurations as needed...
