# netlify.toml

[build]
  command = "(cd client && npm install && npm run build) && npm run build"
  publish = "client/build"  # Adjust the publish directory based on your setup

# Add other configurations as needed...
